wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685754348.806341
    t:
      1:
      - 12
      - 45
      - 55
      3:
      - 23
      4: 3.9.16
      5: 0.15.3
      8:
      - 5
