wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685593433.72991
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 23
      4: 3.9.16
      5: 0.15.3
      8:
      - 5
'?':
  desc: null
  value: false
alsologtostderr:
  desc: null
  value: false
batch_size:
  desc: null
  value: 256
binary_include_bc:
  desc: null
  value: true
checkpoint_buffer:
  desc: null
  value: false
checkpoint_model:
  desc: null
  value: false
chex_assert_multiple_cpu_devices:
  desc: null
  value: false
chex_n_cpu_devices:
  desc: null
  value: 1
chex_skip_pmap_variant_if_single_device:
  desc: null
  value: true
config:
  desc: null
  value: 'actor_lr: 0.0003

    backup_entropy: true

    critic_layer_norm: false

    critic_lr: 0.0003

    critic_weight_decay: null

    discount: 0.99

    hidden_dims: !!python/tuple

    - 256

    - 256

    init_temperature: 1.0

    model_cls: SACLearner

    num_qs: 2

    target_entropy: null

    tau: 0.005

    temp_lr: 0.0003

    '
env_name:
  desc: null
  value: rlproject/RLproject-v0
eval_episodes:
  desc: null
  value: 10
eval_interval:
  desc: null
  value: 5000
help:
  desc: null
  value: false
helpfull:
  desc: null
  value: false
helpshort:
  desc: null
  value: false
helpxml:
  desc: null
  value: false
log_dir:
  desc: null
  value: ''
log_interval:
  desc: null
  value: 1000
logger_levels:
  desc: null
  value: {}
logtostderr:
  desc: null
  value: false
max_steps:
  desc: null
  value: 10
offline_ratio:
  desc: null
  value: 0.5
only_check_args:
  desc: null
  value: false
pdb:
  desc: null
  value: false
pdb_post_mortem:
  desc: null
  value: false
pretrain_steps:
  desc: null
  value: 0
profile_file:
  desc: null
  value: null
project_name:
  desc: null
  value: rlproject
pymjcf_debug:
  desc: null
  value: false
pymjcf_debug_full_dump_dir:
  desc: null
  value: ''
pymjcf_log_xml:
  desc: null
  value: false
run_with_pdb:
  desc: null
  value: false
run_with_profiling:
  desc: null
  value: false
save_video:
  desc: null
  value: false
seed:
  desc: null
  value: 42
showprefixforinfo:
  desc: null
  value: true
start_training:
  desc: null
  value: 5
stderrthreshold:
  desc: null
  value: fatal
test_random_seed:
  desc: null
  value: 301
test_randomize_ordering_seed:
  desc: null
  value: ''
test_srcdir:
  desc: null
  value: ''
test_tmpdir:
  desc: null
  value: /tmp/absl_testing
timeout:
  desc: null
  value: true
tqdm:
  desc: null
  value: true
use_cprofile_for_profiling:
  desc: null
  value: true
utd_ratio:
  desc: null
  value: 1
v:
  desc: null
  value: 0
verbosity:
  desc: null
  value: 0
xml_output_file:
  desc: null
  value: ''
